name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [20]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install
      
    - name: Install FlexCli
      run: npm install -g @eniac/flexcli
      
    - name: Build plugin
      run: npm run build
      
    - name: Test plugin
      run: npm run plugin:pack
      
    - name: Upload build artifacts
      uses: softprops/action-gh-release@v2
      with:
        name: plugin-${{ matrix.os }}
        path: com.energy.spotify_integration.flexplugin 